<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Review;
use App\Models\Setting;
use App\Models\Shop;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Seed Authenticated Users
        $owner = User::factory()->create([
            'name' => 'Eko Susanto',
            'email' => 'owner@serasa.levitation.web.id',
            'password' => Hash::make('password'),
            'role' => 'owner',
        ]);

        User::factory()->admin()->create([
            'name' => 'Admin Desa Samirono',
            'email' => 'admin@serasa.levitation.web.id',
            'password' => Hash::make('password'),
        ]);

        // 2. Seed App Settings
        $settings = [
            'appName' => 'SERASA',
            'tagline' => 'Etalase Kreatif & Digitalisasi UMKM Desa Samirono',
            'villageName' => 'Desa Samirono',
            'description' => 'Wadah promosi digital terpusat untuk memperkenalkan produk-produk ekonomi kreatif unggulan Desa Samirono. Memperluas jangkauan pasar eksternal dan mendigitalisasi pelaku UMKM lokal agar berdaya saing global.',
            'adminPhone' => '6285725912345',
            'heroBanner' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=1600',
        ];

        foreach ($settings as $key => $value) {
            Setting::create(['key' => $key, 'value' => $value]);
        }

        // 3. Seed Categories
        $categories = [
            [
                'id' => 'cat-kuliner',
                'name' => 'Kuliner & Olahan',
                'icon_name' => 'Utensils',
                'description' => 'Makanan tradisional, jajanan pasar khas desa, dan produk olahan lokal.',
                'color' => 'amber',
            ],
            [
                'id' => 'cat-pertanian',
                'name' => 'Pertanian & Susu',
                'icon_name' => 'Sprout',
                'description' => 'Susu sapi segar, keju artisan lokal, dan hasil bumi organik segar.',
                'color' => 'teal',
            ],
            [
                'id' => 'cat-kerajinan',
                'name' => 'Kriya & Kerajinan',
                'icon_name' => 'Hammer',
                'description' => 'Kerajinan tangan dari bambu, anyaman tradisional, dan dekorasi rumah bernilai seni.',
                'color' => 'orange',
            ],
            [
                'id' => 'cat-wisata',
                'name' => 'Wisata & Jasa',
                'icon_name' => 'Compass',
                'description' => 'Sewa homestay, paket edukasi perah susu, outbound, dan pemandu lokal.',
                'color' => 'blue',
            ],
            [
                'id' => 'cat-fashion',
                'name' => 'Fashion & Kain',
                'icon_name' => 'Shirt',
                'description' => 'Batik lokal, pakaian anyaman rajut, dan kerajinan serat kain alami.',
                'color' => 'purple',
            ],
        ];

        foreach ($categories as $cat) {
            Category::create($cat);
        }

        // 4. Seed Real UMKM Shops (Extracted from DATA UMKM 2026.xlsx)
        $shops = [
            [
                'id' => 'shop-bakpia-berkah',
                'name' => 'Bakpia Berkah',
                'owner_name' => 'Eko Susanto',
                'description' => 'Produk UMKM Bakpia Berkah dari Dusun Pongangan, Desa Samirono. Mengolah Bakpia/ Makanan Kering. Pemasaran: Distribusi ke Warung2/ Toko/ Event2 di Kabupaten Semarang.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 04/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => $owner->id,
            ],
            [
                'id' => 'shop-keripik-lintang',
                'name' => 'Keripik Lintang',
                'owner_name' => 'Ratmiatun',
                'description' => 'Produk UMKM Keripik Lintang dari Dusun Tawang, Desa Samirono. Mengolah Aneka Olahan Keripik. Pemasaran: Distribusi ke Warung2/ Toko/ Event2 di Kabupaten Semarang.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Tawang RT 07/ RW 02, Desa Samirono',
                'dusun' => 'Dusun Tawang',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-kempripik',
                'name' => 'Kempripik',
                'owner_name' => 'Umiyati',
                'description' => 'Produk UMKM Kempripik dari Dusun Pongangan, Desa Samirono. Mengolah Keripik Pisang. Pemasaran: Distribusi ke Warung2/ Toko/ Event2 di Kabupaten Semarang.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 01/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-simple-coffee',
                'name' => 'Simple Coffee',
                'owner_name' => 'Darno',
                'description' => 'Produk UMKM Simple Coffee dari Dusun Pongangan, Desa Samirono. Mengolah Olahan Kopi, Café. Pemasaran: Distribusi ke Warung2/ Toko/ Event2 di Kabupaten Semarang.',
                'category' => 'Pertanian & Susu',
                'phone' => null,
                'address' => 'Pongangan RT 01/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => true,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-d-kriuk',
                'name' => 'D\' Kriuk',
                'owner_name' => 'Andriyana',
                'description' => 'Produk UMKM D\' Kriuk dari Dusun Samirono, Desa Samirono. Mengolah Olahan Keripik Usus. Pemasaran: Distribusi ke Warung2/ Toko/ Event2 di Kabupaten Semarang.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Samirono RT 10/ RW 02, Desa Samirono',
                'dusun' => 'Dusun Samirono',
                'image' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-dapur-mutiara',
                'name' => 'Dapur Mutiara',
                'owner_name' => 'Kayati',
                'description' => 'Produk UMKM Dapur Mutiara dari Dusun Pongangan, Desa Samirono. Mengolah Aneka Snack dan Catering. Pemasaran: Pengadaan Snak dan Catering pada rapat2.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 2/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-teh-sangrai-sembada',
                'name' => 'Teh Sangrai Sembada',
                'owner_name' => 'Markhamah',
                'description' => 'Produk UMKM Teh Sangrai Sembada dari Dusun Tawang, Desa Samirono. Mengolah Sangrai The Jawa. Pemasaran: Distribusi ke Warung2/ Toko/ Event2 di Kabupaten Semarang.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Tawang RT 07/ RW 02, Desa Samirono',
                'dusun' => 'Dusun Tawang',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-tempe-daun-andong-ibu-ngatiyem',
                'name' => 'Tempe Daun Andong Ibu Ngatiyem',
                'owner_name' => 'Ngatiyem',
                'description' => 'Produk UMKM Tempe Daun Andong Ibu Ngatiyem dari Dusun Pongangan, Desa Samirono. Mengolah Tempe Daun Andong. Pemasaran: Distribusi ke Pasar Tradisional spt Pasar Kopeng, Pasar Getasan, Pasar Ngablak.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 04/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-sariyem',
                'name' => 'Sariyem',
                'owner_name' => 'Sariyem',
                'description' => 'Produk UMKM Sariyem dari Dusun Samirono, Desa Samirono. Mengolah Risol Mayo, Gendar Pecel, Nasi Jagung. Pemasaran: Pengadaan Snak dan Catering pada rapat2.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Samirono RT 10/ RW 02, Desa Samirono',
                'dusun' => 'Dusun Samirono',
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-tempe-daun-andong-ibu-kasini',
                'name' => 'Tempe Daun Andong Ibu Kasini',
                'owner_name' => 'Kasini',
                'description' => 'Produk UMKM Tempe Daun Andong Ibu Kasini dari Dusun Pongangan, Desa Samirono. Mengolah Tempe Daun Andong. Pemasaran: Distribusi ke Pasar Tradisional spt Pasar Kopeng, Pasar Getasan, Pasar Ngablak.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 04/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-donut',
                'name' => 'Donut',
                'owner_name' => 'Lia Setiyani',
                'description' => 'Produk UMKM Donut dari Dusun Kendal, Desa Samirono. Mengolah Donut.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Kendal RT 06/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Kendal',
                'image' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => false,
                'halal' => false,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-pawon-mamak-alga',
                'name' => 'Pawon Mamak Alga',
                'owner_name' => 'Rohmiati',
                'description' => 'Produk UMKM Pawon Mamak Alga dari Dusun Kendal, Desa Samirono. Mengolah Seblak, Kwetiau, dsb. Pemasaran: Lapak di Rumah.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Kendal RT 06/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Kendal',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-rukimin-tahu',
                'name' => 'Rukimin Tahu',
                'owner_name' => 'Rukimin',
                'description' => 'Produk UMKM Rukimin Tahu dari Dusun Pongangan, Desa Samirono. Mengolah Pabrik Tahu. Pemasaran: Pabrik Tahu Sekala Besar, Distribusi ke Pasar Tradisional.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 02/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-hafidz-kitchen',
                'name' => 'Hafidz Kitchen',
                'owner_name' => 'Rengganis Pratiwi',
                'description' => 'Produk UMKM Hafidz Kitchen dari Dusun Pongangan, Desa Samirono. Mengolah Pengadaan Snak dan Catering, Kue Mochi.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 01/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-jati',
                'name' => 'Jati',
                'owner_name' => 'Jati Nur Kinah',
                'description' => 'Produk UMKM Jati dari Dusun Pongangan, Desa Samirono. Mengolah Keripik Bawang, Kunir Asem, Tahu Baso. Pemasaran: Distribusi ke Warung2/ Toko/ Event2 di Kabupaten Semarang.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 02/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-timus-lumer',
                'name' => 'Timus Lumer',
                'owner_name' => 'Puani',
                'description' => 'Produk UMKM Timus Lumer dari Dusun Pongangan, Desa Samirono. Mengolah Timus Lumer, Tahu Sakura.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 01/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-daniel-snack',
                'name' => 'Daniel Snack',
                'owner_name' => 'Daniel Winardji',
                'description' => 'Produk UMKM Daniel Snack dari Dusun Tawang, Desa Samirono. Mengolah Pengadaan Snak dan Catering. Pemasaran: Pengadaan Snak dan Catering pada rapat2.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Tawang RT 08/ RW 02, Desa Samirono',
                'dusun' => 'Dusun Tawang',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-kopi-guci',
                'name' => 'Kopi Guci',
                'owner_name' => 'Thomas Tukiyat',
                'description' => 'Produk UMKM Kopi Guci dari Dusun Kendal, Desa Samirono. Mengolah Kopi. Pemasaran: Distribusi ke Warung2/ Toko/ Event2 di Kabupaten Semarang.',
                'category' => 'Pertanian & Susu',
                'phone' => null,
                'address' => 'Kendal RT 06/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Kendal',
                'image' => 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => true,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-cumilk-kita',
                'name' => 'Cumilk Kita',
                'owner_name' => 'Kelompok PKK RT 09',
                'description' => 'Produk UMKM Cumilk Kita dari Dusun Samirono, Desa Samirono. Mengolah Permen Susu. Pemasaran: distribusi Permen susu kesesama anggota, pada event2 desa, danpameran kabupaten.',
                'category' => 'Pertanian & Susu',
                'phone' => null,
                'address' => 'Samirono RT 09 RW 02, Desa Samirono',
                'dusun' => 'Dusun Samirono',
                'image' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-sabun-susu-samirono',
                'name' => 'Sabun Susu Samirono',
                'owner_name' => 'Kelompok PKK Dusun Pongangan',
                'description' => 'Produk UMKM Sabun Susu Samirono dari Dusun Pongangan, Desa Samirono. Mengolah sabun Susu. Pemasaran: Event Desa dan Kabupaten.',
                'category' => 'Pertanian & Susu',
                'phone' => null,
                'address' => 'Pongangan, Samirono, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => false,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-sisuka-bake-s',
                'name' => 'Sisuka Bake\'s',
                'owner_name' => 'Siska',
                'description' => 'Produk UMKM Sisuka Bake\'s dari Dusun Samirono, Desa Samirono. Mengolah Aneka Kue dan tart.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Samirono RT 10/ RW 02, Desa Samirono',
                'dusun' => 'Dusun Samirono',
                'image' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-pisang-lumer',
                'name' => 'Pisang Lumer',
                'owner_name' => 'Sofi',
                'description' => 'Produk UMKM Pisang Lumer dari Dusun Pongangan, Desa Samirono. Mengolah keripik Pisang Lumer. Pemasaran: Distribusi ke Warung2/ Toko/ Event2 di Kabupaten Semarang.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 03/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => true,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-warung-ibu-supartini',
                'name' => 'Warung Ibu Supartini',
                'owner_name' => 'Supartini',
                'description' => 'Produk UMKM Warung Ibu Supartini dari Dusun Pongangan, Desa Samirono. Mengolah Bubur Tumpang, Sate, aneka Snack Tradisional. Pemasaran: Lapak di Rumah.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 03/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => false,
                'halal' => false,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-keripik-bawang-ibu-tri-mutiah',
                'name' => 'Keripik Bawang Ibu Tri Mutiah',
                'owner_name' => 'Tri Mutiah',
                'description' => 'Produk UMKM Keripik Bawang Ibu Tri Mutiah dari Dusun Pongangan, Desa Samirono. Mengolah Keripik Bawang.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 03/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => false,
                'halal' => false,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-tempe-daun-ibu-sutini',
                'name' => 'Tempe Daun Ibu Sutini',
                'owner_name' => 'Sutini',
                'description' => 'Produk UMKM Tempe Daun Ibu Sutini dari Dusun Pongangan, Desa Samirono. Mengolah Tempe Daun Andong. Pemasaran: Distribusi ke pasar tradisional.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 01/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-yoghurt',
                'name' => 'Yoghurt',
                'owner_name' => 'Piyati',
                'description' => 'Produk UMKM Yoghurt dari Dusun Samirono, Desa Samirono. Mengolah Yoghurt. Pemasaran: Distribusi hingga ke luar kabupaten Semarang.',
                'category' => 'Pertanian & Susu',
                'phone' => null,
                'address' => 'Samirono RT 10/ RW 02, Desa Samirono',
                'dusun' => 'Dusun Samirono',
                'image' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => true,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-warung-ibu-endah-anita-sari',
                'name' => 'Warung Ibu Endah Anita sari',
                'owner_name' => 'Endah Anita sari',
                'description' => 'Produk UMKM Warung Ibu Endah Anita sari dari Dusun Samirono, Desa Samirono. Mengolah Seblak, Kwetiau, dsb. Pemasaran: Lapak di Rumah.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Samirono RT 10/ RW 02, Desa Samirono',
                'dusun' => 'Dusun Samirono',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => false,
                'halal' => false,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-kue-kacang',
                'name' => 'Kue Kacang',
                'owner_name' => 'Etik',
                'description' => 'Produk UMKM Kue Kacang dari Dusun Pongangan, Desa Samirono. Mengolah Kue Kacang. Pemasaran: Distribusi ke Warung2/ Toko/ Event2 di Kabupaten Semarang.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 03/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-gethuk-eco-roso',
                'name' => 'Gethuk Eco Roso',
                'owner_name' => 'Marsih',
                'description' => 'Produk UMKM Gethuk Eco Roso dari Dusun Watulawang, Desa Samirono. Mengolah Aneka Gethuk Krispi. Pemasaran: Distribusi hingga ke luar kabupaten Semarang.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Watulawang RT 13/ RW 03, Desa Samirono',
                'dusun' => 'Dusun Watulawang',
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => true,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-nafara-sayur',
                'name' => 'Nafara Sayur',
                'owner_name' => 'Pemilik Nafara Sayur',
                'description' => 'Produk UMKM Nafara Sayur dari Dusun Pongangan, Desa Samirono. Mengolah Tiwul dan sayur Keliling. Pemasaran: Buka Lapak di Rumah dan Keliling.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 04/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-milky-jong',
                'name' => 'Milky Jong',
                'owner_name' => 'Sri Sulasmi',
                'description' => 'Produk UMKM Milky Jong dari Dusun Samirono, Desa Samirono. Mengolah Susu Pasteurisasi, Es Susu Lumut, Nasi Goreng, Kwetiau, Dsb. Pemasaran: Buka Lapak di Rumah.',
                'category' => 'Pertanian & Susu',
                'phone' => null,
                'address' => 'Samirono RT 11/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Samirono',
                'image' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-resep-e-mak-e',
                'name' => 'Resep E Mak E',
                'owner_name' => 'Ngatini',
                'description' => 'Produk UMKM Resep E Mak E dari Dusun Pongangan, Desa Samirono. Mengolah Geplak Jagung. Pemasaran: -.',
                'category' => 'Kuliner & Olahan',
                'phone' => null,
                'address' => 'Pongangan RT 01/ RW 01, Desa Samirono',
                'dusun' => 'Dusun Pongangan',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => false,
                'halal' => false,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
            [
                'id' => 'shop-dapur-may-familly',
                'name' => 'Dapur May Familly',
                'owner_name' => 'Rosi',
                'description' => 'Produk UMKM Dapur May Familly dari Dusun Samirono, Desa Samirono. Mengolah Bolu Susu. Pemasaran: Buka Lapak di rumah.',
                'category' => 'Pertanian & Susu',
                'phone' => null,
                'address' => 'Desa Samirono',
                'dusun' => 'Dusun Samirono',
                'image' => 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&q=80&w=800',
                'logo' => 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&q=80&w=800',
                'is_verified' => true,
                'nib' => true,
                'halal' => true,
                'pirt' => false,
                'lat' => null,
                'lng' => null,
                'working_hours' => '08:00 - 17:00',
                'user_id' => null,
            ],
        ];

        foreach ($shops as $shop) {
            Shop::create($shop);
        }

        // 5. Seed Products for UMKM Shops
        $products = [
            [
                'id' => 'prod-bakpia-berkah',
                'shop_id' => 'shop-bakpia-berkah',
                'category_id' => 'cat-kuliner',
                'name' => 'Bakpia/ Makanan Kering',
                'description' => 'Produk unggulan Bakpia Berkah dari Dusun Pongangan, Desa Samirono. Bakpia/ Makanan Kering.',
                'price' => 15000,
                'unit' => 'Bungkus',
                'image' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                    'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                    'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                ],
                'rating' => 4.6,
                'reviews_count' => 1,
                'is_available' => true,
            ],
            [
                'id' => 'prod-keripik-lintang',
                'shop_id' => 'shop-keripik-lintang',
                'category_id' => 'cat-kuliner',
                'name' => 'Aneka Olahan Keripik',
                'description' => 'Produk unggulan Keripik Lintang dari Dusun Tawang, Desa Samirono. Aneka Olahan Keripik.',
                'price' => 15000,
                'unit' => 'Bungkus',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                    'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
                ],
                'rating' => 4.7,
                'reviews_count' => 2,
                'is_available' => true,
            ],
            [
                'id' => 'prod-kempripik',
                'shop_id' => 'shop-kempripik',
                'category_id' => 'cat-kuliner',
                'name' => 'Keripik Pisang',
                'description' => 'Produk unggulan Kempripik dari Dusun Pongangan, Desa Samirono. Keripik Pisang.',
                'price' => 15000,
                'unit' => 'Bungkus',
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                    'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                ],
                'rating' => 4.8,
                'reviews_count' => 0,
                'is_available' => true,
            ],
            [
                'id' => 'prod-simple-coffee',
                'shop_id' => 'shop-simple-coffee',
                'category_id' => 'cat-pertanian',
                'name' => 'Olahan Kopi, Café',
                'description' => 'Produk unggulan Simple Coffee dari Dusun Pongangan, Desa Samirono. Olahan Kopi, Café.',
                'price' => 25000,
                'unit' => 'Pack',
                'image' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800',
                    'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&q=80&w=800',
                ],
                'rating' => 4.9,
                'reviews_count' => 1,
                'is_available' => true,
            ],
            [
                'id' => 'prod-d-kriuk',
                'shop_id' => 'shop-d-kriuk',
                'category_id' => 'cat-kuliner',
                'name' => 'Olahan Keripik Usus',
                'description' => 'Produk unggulan D\' Kriuk dari Dusun Samirono, Desa Samirono. Olahan Keripik Usus.',
                'price' => 15000,
                'unit' => 'Bungkus',
                'image' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                    'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                ],
                'rating' => 5.0,
                'reviews_count' => 2,
                'is_available' => true,
            ],
            [
                'id' => 'prod-dapur-mutiara',
                'shop_id' => 'shop-dapur-mutiara',
                'category_id' => 'cat-kuliner',
                'name' => 'Aneka Snack dan Catering',
                'description' => 'Produk unggulan Dapur Mutiara dari Dusun Pongangan, Desa Samirono. Aneka Snack dan Catering.',
                'price' => 15000,
                'unit' => 'Pcs',
                'image' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.5,
                'reviews_count' => 0,
                'is_available' => true,
            ],
            [
                'id' => 'prod-teh-sangrai-sembada',
                'shop_id' => 'shop-teh-sangrai-sembada',
                'category_id' => 'cat-kuliner',
                'name' => 'Sangrai The Jawa',
                'description' => 'Produk unggulan Teh Sangrai Sembada dari Dusun Tawang, Desa Samirono. Sangrai The Jawa.',
                'price' => 15000,
                'unit' => 'Pcs',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.6,
                'reviews_count' => 1,
                'is_available' => true,
            ],
            [
                'id' => 'prod-tempe-daun-andong-ibu-ngatiyem',
                'shop_id' => 'shop-tempe-daun-andong-ibu-ngatiyem',
                'category_id' => 'cat-kuliner',
                'name' => 'Tempe Daun Andong',
                'description' => 'Produk unggulan Tempe Daun Andong Ibu Ngatiyem dari Dusun Pongangan, Desa Samirono. Tempe Daun Andong.',
                'price' => 10000,
                'unit' => 'Porsi',
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.7,
                'reviews_count' => 2,
                'is_available' => true,
            ],
            [
                'id' => 'prod-sariyem',
                'shop_id' => 'shop-sariyem',
                'category_id' => 'cat-kuliner',
                'name' => 'Risol Mayo, Gendar Pecel, Nasi Jagung',
                'description' => 'Produk unggulan Sariyem dari Dusun Samirono, Desa Samirono. Risol Mayo, Gendar Pecel, Nasi Jagung.',
                'price' => 15000,
                'unit' => 'Pcs',
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.8,
                'reviews_count' => 0,
                'is_available' => true,
            ],
            [
                'id' => 'prod-tempe-daun-andong-ibu-kasini',
                'shop_id' => 'shop-tempe-daun-andong-ibu-kasini',
                'category_id' => 'cat-kuliner',
                'name' => 'Tempe Daun Andong',
                'description' => 'Produk unggulan Tempe Daun Andong Ibu Kasini dari Dusun Pongangan, Desa Samirono. Tempe Daun Andong.',
                'price' => 10000,
                'unit' => 'Porsi',
                'image' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.9,
                'reviews_count' => 1,
                'is_available' => true,
            ],
            [
                'id' => 'prod-donut',
                'shop_id' => 'shop-donut',
                'category_id' => 'cat-kuliner',
                'name' => 'Donut',
                'description' => 'Produk unggulan Donut dari Dusun Kendal, Desa Samirono. Donut.',
                'price' => 15000,
                'unit' => 'Pcs',
                'image' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'rating' => 5.0,
                'reviews_count' => 2,
                'is_available' => true,
            ],
            [
                'id' => 'prod-pawon-mamak-alga',
                'shop_id' => 'shop-pawon-mamak-alga',
                'category_id' => 'cat-kuliner',
                'name' => 'Seblak, Kwetiau, dsb',
                'description' => 'Produk unggulan Pawon Mamak Alga dari Dusun Kendal, Desa Samirono. Seblak, Kwetiau, dsb.',
                'price' => 10000,
                'unit' => 'Porsi',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.5,
                'reviews_count' => 0,
                'is_available' => true,
            ],
            [
                'id' => 'prod-rukimin-tahu',
                'shop_id' => 'shop-rukimin-tahu',
                'category_id' => 'cat-kuliner',
                'name' => 'Pabrik Tahu',
                'description' => 'Produk unggulan Rukimin Tahu dari Dusun Pongangan, Desa Samirono. Pabrik Tahu.',
                'price' => 10000,
                'unit' => 'Porsi',
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.6,
                'reviews_count' => 1,
                'is_available' => true,
            ],
            [
                'id' => 'prod-hafidz-kitchen',
                'shop_id' => 'shop-hafidz-kitchen',
                'category_id' => 'cat-kuliner',
                'name' => 'Pengadaan Snak dan Catering, Kue Mochi',
                'description' => 'Produk unggulan Hafidz Kitchen dari Dusun Pongangan, Desa Samirono. Pengadaan Snak dan Catering, Kue Mochi.',
                'price' => 25000,
                'unit' => 'Pack',
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.7,
                'reviews_count' => 2,
                'is_available' => true,
            ],
            [
                'id' => 'prod-jati',
                'shop_id' => 'shop-jati',
                'category_id' => 'cat-kuliner',
                'name' => 'Keripik Bawang, Kunir Asem, Tahu Baso',
                'description' => 'Produk unggulan Jati dari Dusun Pongangan, Desa Samirono. Keripik Bawang, Kunir Asem, Tahu Baso.',
                'price' => 10000,
                'unit' => 'Porsi',
                'image' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.8,
                'reviews_count' => 0,
                'is_available' => true,
            ],
            [
                'id' => 'prod-timus-lumer',
                'shop_id' => 'shop-timus-lumer',
                'category_id' => 'cat-kuliner',
                'name' => 'Timus Lumer, Tahu Sakura',
                'description' => 'Produk unggulan Timus Lumer dari Dusun Pongangan, Desa Samirono. Timus Lumer, Tahu Sakura.',
                'price' => 10000,
                'unit' => 'Porsi',
                'image' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.9,
                'reviews_count' => 1,
                'is_available' => true,
            ],
            [
                'id' => 'prod-daniel-snack',
                'shop_id' => 'shop-daniel-snack',
                'category_id' => 'cat-kuliner',
                'name' => 'Pengadaan Snak dan Catering',
                'description' => 'Produk unggulan Daniel Snack dari Dusun Tawang, Desa Samirono. Pengadaan Snak dan Catering.',
                'price' => 15000,
                'unit' => 'Pcs',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'rating' => 5.0,
                'reviews_count' => 2,
                'is_available' => true,
            ],
            [
                'id' => 'prod-kopi-guci',
                'shop_id' => 'shop-kopi-guci',
                'category_id' => 'cat-pertanian',
                'name' => 'Kopi',
                'description' => 'Produk unggulan Kopi Guci dari Dusun Kendal, Desa Samirono. Kopi.',
                'price' => 25000,
                'unit' => 'Pack',
                'image' => 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.5,
                'reviews_count' => 0,
                'is_available' => true,
            ],
            [
                'id' => 'prod-cumilk-kita',
                'shop_id' => 'shop-cumilk-kita',
                'category_id' => 'cat-pertanian',
                'name' => 'Permen Susu',
                'description' => 'Produk unggulan Cumilk Kita dari Dusun Samirono, Desa Samirono. Permen Susu.',
                'price' => 15000,
                'unit' => 'Bungkus',
                'image' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.6,
                'reviews_count' => 1,
                'is_available' => true,
            ],
            [
                'id' => 'prod-sabun-susu-samirono',
                'shop_id' => 'shop-sabun-susu-samirono',
                'category_id' => 'cat-pertanian',
                'name' => 'sabun Susu',
                'description' => 'Produk unggulan Sabun Susu Samirono dari Dusun Pongangan, Desa Samirono. sabun Susu.',
                'price' => 20000,
                'unit' => 'Pcs',
                'image' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.7,
                'reviews_count' => 2,
                'is_available' => true,
            ],
            [
                'id' => 'prod-sisuka-bake-s',
                'shop_id' => 'shop-sisuka-bake-s',
                'category_id' => 'cat-kuliner',
                'name' => 'Aneka Kue dan tart',
                'description' => 'Produk unggulan Sisuka Bake\'s dari Dusun Samirono, Desa Samirono. Aneka Kue dan tart.',
                'price' => 25000,
                'unit' => 'Pack',
                'image' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.8,
                'reviews_count' => 0,
                'is_available' => true,
            ],
            [
                'id' => 'prod-pisang-lumer',
                'shop_id' => 'shop-pisang-lumer',
                'category_id' => 'cat-kuliner',
                'name' => 'keripik Pisang Lumer',
                'description' => 'Produk unggulan Pisang Lumer dari Dusun Pongangan, Desa Samirono. keripik Pisang Lumer.',
                'price' => 15000,
                'unit' => 'Bungkus',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.9,
                'reviews_count' => 1,
                'is_available' => true,
            ],
            [
                'id' => 'prod-warung-ibu-supartini',
                'shop_id' => 'shop-warung-ibu-supartini',
                'category_id' => 'cat-kuliner',
                'name' => 'Bubur Tumpang, Sate, aneka Snack Tradisional',
                'description' => 'Produk unggulan Warung Ibu Supartini dari Dusun Pongangan, Desa Samirono. Bubur Tumpang, Sate, aneka Snack Tradisional.',
                'price' => 15000,
                'unit' => 'Pcs',
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'rating' => 5.0,
                'reviews_count' => 2,
                'is_available' => true,
            ],
            [
                'id' => 'prod-keripik-bawang-ibu-tri-mutiah',
                'shop_id' => 'shop-keripik-bawang-ibu-tri-mutiah',
                'category_id' => 'cat-kuliner',
                'name' => 'Keripik Bawang',
                'description' => 'Produk unggulan Keripik Bawang Ibu Tri Mutiah dari Dusun Pongangan, Desa Samirono. Keripik Bawang.',
                'price' => 15000,
                'unit' => 'Bungkus',
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.5,
                'reviews_count' => 0,
                'is_available' => true,
            ],
            [
                'id' => 'prod-tempe-daun-ibu-sutini',
                'shop_id' => 'shop-tempe-daun-ibu-sutini',
                'category_id' => 'cat-kuliner',
                'name' => 'Tempe Daun Andong',
                'description' => 'Produk unggulan Tempe Daun Ibu Sutini dari Dusun Pongangan, Desa Samirono. Tempe Daun Andong.',
                'price' => 10000,
                'unit' => 'Porsi',
                'image' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.6,
                'reviews_count' => 1,
                'is_available' => true,
            ],
            [
                'id' => 'prod-yoghurt',
                'shop_id' => 'shop-yoghurt',
                'category_id' => 'cat-pertanian',
                'name' => 'Yoghurt',
                'description' => 'Produk unggulan Yoghurt dari Dusun Samirono, Desa Samirono. Yoghurt.',
                'price' => 15000,
                'unit' => 'Pcs',
                'image' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.7,
                'reviews_count' => 2,
                'is_available' => true,
            ],
            [
                'id' => 'prod-warung-ibu-endah-anita-sari',
                'shop_id' => 'shop-warung-ibu-endah-anita-sari',
                'category_id' => 'cat-kuliner',
                'name' => 'Seblak, Kwetiau, dsb',
                'description' => 'Produk unggulan Warung Ibu Endah Anita sari dari Dusun Samirono, Desa Samirono. Seblak, Kwetiau, dsb.',
                'price' => 10000,
                'unit' => 'Porsi',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.8,
                'reviews_count' => 0,
                'is_available' => true,
            ],
            [
                'id' => 'prod-kue-kacang',
                'shop_id' => 'shop-kue-kacang',
                'category_id' => 'cat-kuliner',
                'name' => 'Kue Kacang',
                'description' => 'Produk unggulan Kue Kacang dari Dusun Pongangan, Desa Samirono. Kue Kacang.',
                'price' => 25000,
                'unit' => 'Pack',
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.9,
                'reviews_count' => 1,
                'is_available' => true,
            ],
            [
                'id' => 'prod-gethuk-eco-roso',
                'shop_id' => 'shop-gethuk-eco-roso',
                'category_id' => 'cat-kuliner',
                'name' => 'Aneka Gethuk Krispi',
                'description' => 'Produk unggulan Gethuk Eco Roso dari Dusun Watulawang, Desa Samirono. Aneka Gethuk Krispi.',
                'price' => 25000,
                'unit' => 'Pack',
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
                'rating' => 5.0,
                'reviews_count' => 2,
                'is_available' => true,
            ],
            [
                'id' => 'prod-nafara-sayur',
                'shop_id' => 'shop-nafara-sayur',
                'category_id' => 'cat-kuliner',
                'name' => 'Tiwul dan sayur Keliling',
                'description' => 'Produk unggulan Nafara Sayur dari Dusun Pongangan, Desa Samirono. Tiwul dan sayur Keliling.',
                'price' => 15000,
                'unit' => 'Pcs',
                'image' => 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.5,
                'reviews_count' => 0,
                'is_available' => true,
            ],
            [
                'id' => 'prod-milky-jong',
                'shop_id' => 'shop-milky-jong',
                'category_id' => 'cat-pertanian',
                'name' => 'Susu Pasteurisasi, Es Susu Lumut, Nasi Goreng, Kwetiau, Dsb',
                'description' => 'Produk unggulan Milky Jong dari Dusun Samirono, Desa Samirono. Susu Pasteurisasi, Es Susu Lumut, Nasi Goreng, Kwetiau, Dsb.',
                'price' => 15000,
                'unit' => 'Pcs',
                'image' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.6,
                'reviews_count' => 1,
                'is_available' => true,
            ],
            [
                'id' => 'prod-resep-e-mak-e',
                'shop_id' => 'shop-resep-e-mak-e',
                'category_id' => 'cat-kuliner',
                'name' => 'Geplak Jagung',
                'description' => 'Produk unggulan Resep E Mak E dari Dusun Pongangan, Desa Samirono. Geplak Jagung.',
                'price' => 15000,
                'unit' => 'Pcs',
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.7,
                'reviews_count' => 2,
                'is_available' => true,
            ],
            [
                'id' => 'prod-dapur-may-familly',
                'shop_id' => 'shop-dapur-may-familly',
                'category_id' => 'cat-pertanian',
                'name' => 'Bolu Susu',
                'description' => 'Produk unggulan Dapur May Familly dari Dusun Samirono, Desa Samirono. Bolu Susu.',
                'price' => 15000,
                'unit' => 'Pcs',
                'image' => 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&q=80&w=800',
                'rating' => 4.8,
                'reviews_count' => 0,
                'is_available' => true,
            ],
        ];

        foreach ($products as $prod) {
            Product::create($prod);
        }

        // 6. Seed Reviews
        $reviews = [
            [
                'id' => 'rev-1',
                'product_id' => 'prod-bakpia-berkah',
                'user_name' => 'Andri Setiawan (Semarang)',
                'rating' => 5,
                'comment' => 'Produk Bakpia Berkah rasanya mantap dan gurih. Pengemasan rapi dan pelayanan cepat!',
            ],
            [
                'id' => 'rev-2',
                'product_id' => 'prod-simple-coffee',
                'user_name' => 'Budi Santoso',
                'rating' => 5,
                'comment' => 'Kopi Simple Coffee khas Desa Samirono aromanya nikmat sekali, mantap!',
            ],
            [
                'id' => 'rev-3',
                'product_id' => 'prod-cumilk-kita',
                'user_name' => 'Siti Rahma',
                'rating' => 5,
                'comment' => 'Permen susu Cumilk Kita kesukaan anak-anak. Manisnya pas dan legit.',
            ],
        ];

        foreach ($reviews as $rev) {
            Review::create($rev);
        }
    }
}
